# Generated by Django 3.1.2 on 2020-11-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='price')),
                ('platform', models.CharField(max_length=100, verbose_name='platform')),
                ('developer', models.CharField(max_length=100, verbose_name='developer')),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
