# Generated by Django 3.1.2 on 2020-11-04 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_experience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='gameId',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='userId',
            new_name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
    ]
