# Generated by Django 3.1.2 on 2020-11-20 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201108_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='price',
        ),
        migrations.CreateModel(
            name='Game_Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(verbose_name='Price')),
                ('platform', models.CharField(max_length=100, verbose_name='Platform')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
            options={
                'db_table': 'game_platform',
            },
        ),
    ]
