# Generated by Django 3.1.2 on 2020-11-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201120_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='steamId',
            field=models.IntegerField(default=0, verbose_name='SteamId'),
            preserve_default=False,
        ),
    ]
