# Generated by Django 3.1.3 on 2020-12-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_game_steamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='rating',
            field=models.IntegerField(verbose_name='Rating'),
        ),
    ]
